//! Card enum for type-safe card references

#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash)]
pub enum CardEnum {
    // Ironclad Cards
    Strike,
    Defend,
    Bash,
    BodySlam,
    Clash,
    Carnage,
    Cleave,
    Embrace,
    Flex,
    Inflame,
    Immolate,
    IronWave,
    PommelStrike,
    ShrugItOff,
    TwinStrike,
    Clothesline,
    HeavyBlade,
    PerfectedStrike,
    Thunderclap,
    WildStrike,
    Combust,
    Disarm,
    Dropkick,
    FeelNoPain,
    Entrench,
    Bludgeon,
    Anger,
    SwordBoomerang,
    Hemokinesis,
    Armaments,
    Impervious,
    Brutality,
    Offering,
    Shockwave,
    Uppercut,
    Intimidate,
    SeeingRed,
    GhostlyArmor,
    Havoc,
    Headbutt,
    TrueGrit,
    Warcry,
    Corruption,
    LimitBreak,
    Metallicize,
    FlameBarrier,
    Rage,
    Rampage,
    InfernalBlade,
    Evolve,
    Sentinel,
    Whirlwind,
    DemonForm,
    SecondWind,
    Rupture,
    // Status Cards
    Slimed,
    Wound,
    Burn,
    // Add more cards as needed
}

impl CardEnum {
    /// Get the display name for this card
    pub fn name(&self) -> &'static str {
        match self {
            CardEnum::Strike => "Strike",
            CardEnum::Defend => "Defend",
            CardEnum::Bash => "Bash",
            CardEnum::BodySlam => "Body Slam",
            CardEnum::Clash => "Clash",
            CardEnum::Carnage => "Carnage",
            CardEnum::Cleave => "Cleave",
            CardEnum::Embrace => "Embrace",
            CardEnum::Flex => "Flex",
            CardEnum::Inflame => "Inflame",
            CardEnum::Immolate => "Immolate",
            CardEnum::IronWave => "IronWave",
            CardEnum::PommelStrike => "PommelStrike",
            CardEnum::ShrugItOff => "ShrugItOff",
            CardEnum::TwinStrike => "TwinStrike",
            CardEnum::Clothesline => "Clothesline",
            CardEnum::HeavyBlade => "HeavyBlade",
            CardEnum::PerfectedStrike => "PerfectedStrike",
            CardEnum::Thunderclap => "Thunderclap",
            CardEnum::WildStrike => "WildStrike",
            CardEnum::Combust => "Combust",
            CardEnum::Disarm => "Disarm",
            CardEnum::Dropkick => "Dropkick",
            CardEnum::FeelNoPain => "Feel No Pain",
            CardEnum::Entrench => "Entrench",
            CardEnum::Bludgeon => "Bludgeon",
            CardEnum::Anger => "Anger",
            CardEnum::SwordBoomerang => "Sword Boomerang",
            CardEnum::Hemokinesis => "Hemokinesis",
            CardEnum::Armaments => "Armaments",
            CardEnum::Impervious => "Impervious",
            CardEnum::Brutality => "Brutality",
            CardEnum::Offering => "Offering",
            CardEnum::Shockwave => "Shockwave",
            CardEnum::Uppercut => "Uppercut",
            CardEnum::Intimidate => "Intimidate",
            CardEnum::SeeingRed => "Seeing Red",
            CardEnum::GhostlyArmor => "Ghostly Armor",
            CardEnum::Havoc => "Havoc",
            CardEnum::Headbutt => "Headbutt",
            CardEnum::TrueGrit => "True Grit",
            CardEnum::Warcry => "Warcry",
            CardEnum::Corruption => "Corruption",
            CardEnum::LimitBreak => "Limit Break",
            CardEnum::Metallicize => "Metallicize",
            CardEnum::FlameBarrier => "Flame Barrier",
            CardEnum::Rage => "Rage",
            CardEnum::Rampage => "Rampage",
            CardEnum::InfernalBlade => "Infernal Blade",
            CardEnum::Evolve => "Evolve",
            CardEnum::Sentinel => "Sentinel",
            CardEnum::Whirlwind => "Whirlwind",
            CardEnum::DemonForm => "Demon Form",
            CardEnum::SecondWind => "Second Wind",
            CardEnum::Rupture => "Rupture",
            CardEnum::Slimed => "Slimed",
            CardEnum::Wound => "Wound",
            CardEnum::Burn => "Burn",
        }
    }
    
    /// Get the upgraded name for this card
    pub fn upgraded_name(&self) -> String {
        format!("{}+", self.name())
    }
}